dj_token = "MTUyMzMwMTMyMDcyNjAyNDIzMw.G1voph.o60bTj-QJWtVyQw_BEruwKLu0IjNbJ0B7RlSgs"

color = 3092790

sync_commands = true

log_channel_id = ""

[database]
host = "postgres.railway.internal"
port = "5432"
user = "postgres"
password = "wNxPMBNadoXSvzNhHgKunyuwngiwqucL"
dbname = "railway"

[[discord_nodes]]
token = "MTUyMzMwMjY1MDgwMjYwMjEzNA.GEQK4J.7vF2Nd2vD2_Xdn0FNugNKWujeVXzouGWZsyZL0"

[[lavalink_nodes]]
name = "main"
address = "diplomatic-encouragement-production-f8c7.up.railway.app"
password = "password"
secure = false
