dj_token = ""

color = 3092790

sync_commands = true

log_channel_id = ""

[database]
host = "postgres.railway.internal"
port = "5432"
user = "postgres"
password = ""
dbname = ""

[[discord_nodes]]
token = ""

[[lavalink_nodes]]
name = "main"
address = "diplomatic-encouragement-production-f8c7.up.railway.app:8080"
password = "password"
secure = false
